[tool.ruff]
target-version = "py313"
line-length = 120
exclude = ["venv", ".venv", "tests", ".pytest_cache", "__pycache__", ".ruff_cache"]

[tool.ruff.lint]
select = ["E", "F", "D", "N"]
ignore = ["D203", "D213", "D401", "D107", "D100", "D415", "D202", "D413", "D205"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["E402"]
